### PR TITLE
Added proxy to error page option and redirection generation

### PR DESCRIPTION
**Pull request by Vitals9367**

### CODE REVIEW

**Review by koskinenaa — COMMENTED** [review]
ok

**Comment by koskinenaa** [comment]
@Vitals9367 I had now proper time to poke around the test site and something is wonky with the redirects.

The login page url, https://portaali202310041helfi.dev.hel.ninja/wp-login.php causes a redirect loop and the general admin path https://portaali202310041helfi.dev.hel.ninja/wp-admin/ gets redirected to the front page instead of the login page where it usually goes, if you're not logged in.

**Comment by Vitals9367** [comment]
@koskinenaa I checked the configuration and readded the .htaccess file. However redirects are put in separate config file which by default is included in the main httpd.conf file. Tested redirects and login page, seems to work now. Please have a second try.

**Review by koskinenaa — COMMENTED** [review]
ok

**Pull request merged**
